version: '3'
services:
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"

  user-service:
    build: ./user-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=userdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=productdb_new
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456

  order-service:
    build: ./order-service
    ports:
      - "8084:8084"
    depends_on:
      - discovery-server
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=orderdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server

volumes:
  discovery-server:
  user-service:
  product-service:
  order-service:
  api-gateway:
